# Generated by Django 4.0.5 on 2022-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_league_password_league_league_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(default=''),
        ),
    ]
