# Generated by Django 4.0.5 on 2022-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
