# Generated by Django 4.0.5 on 2022-06-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_league_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='api.season'),
        ),
    ]
