# Generated by Django 4.0.5 on 2022-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_season_season_year_alter_league_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='num_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='api.season'),
        ),
    ]
